package com.sx.picScale.dao;

import com.sx.picScale.entity.Picpath;

public interface PicpathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picpath
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picpath
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    int insert(Picpath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picpath
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    int insertSelective(Picpath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picpath
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */

    Picpath selectByPrimaryKey(Long id);
    Picpath selectBySrc(String src);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picpath
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    int updateByPrimaryKeySelective(Picpath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picpath
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    int updateByPrimaryKey(Picpath record);
}