package com.sx.picScale.entity;

public class Picpath {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picpath.id
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picpath.src
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picpath.id
     *
     * @return the value of picpath.id
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picpath.id
     *
     * @param id the value for picpath.id
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picpath.src
     *
     * @return the value of picpath.src
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picpath.src
     *
     * @param src the value for picpath.src
     *
     * @mbg.generated Wed Jul 26 09:58:48 CST 2017
     */
    public void setSrc(String src) {
        this.src = src;
    }
}